---
abstract: 'PRANG implementation of the XML SRS protocol'
author:
  - 'Catalyst SRS Team <team-srs@catalyst.net.nz>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  XML::Compare: 0.02
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.95'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-SRS
no_index:
  directory:
    - inc
    - t
requires:
  Crypt::Password: 0.05
  Moose: 0.54
  MooseX::Method::Signatures: 0
  MooseX::Timestamp: 0
  PRANG: 0.09
  Regexp::Common: 0
resources:
  license: http://opensource.org/licenses/artistic-license.php
version: 0.03
