---
abstract: 'PRANG implementation of the XML SRS protocol'
author:
  - 'Catalyst SRS Team <team-srs@catalyst.net.nz>'
build_requires:
  XML::Compare: 0.03
distribution_type: module
generated_by: 'Module::Install version 0.76'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-SRS
no_index:
  directory:
    - inc
    - t
requires:
  Crypt::Password: 0.05
  Moose: 0.54
  MooseX::Method::Signatures: 0
  MooseX::Timestamp: 0
  PRANG: 0.1
  Regexp::Common: 0
version: 0.04
